<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
        
        
        
        
            <?php echo $this->translate('Home'); ?>
            <?php echo $this->translate('Armazem'); ?>
            <br><br><br>
            
            <?php 
              /*   echo $this->dateFormat(
	              new DateTime(),
                  IntlDateFormatter::MEDIUM,
                  IntlDateFormatter::NONE,
                  "pt_BR" 
                ); */

                /* $this->plugin("dateFormat")->setTimezone("America/Sao_Paulo")->setLocale("pt_BR");
                echo $this->dateFormat(new DateTime,IntlDateFormatter::MEDIUM,IntlDateFormatter::MEDIUM); */

                
                 echo $this->numberFormat(
                    1234.56789,
                  NumberFormatter::DECIMAL,
                  NumberFormatter::TYPE_DEFAULT,
                  "pt_BR" 
                )."<br>";

                echo $this->numberFormat(
		          0.8451464143673452871513230546579,
		          NumberFormatter::SCIENTIFIC,
		          NumberFormatter::TYPE_DEFAULT,
		          "pt_BR"
                )."<br>";

                echo $this->currencyFormat(
            		12.3,
            		'BRL'
                     )."<br>";

                echo $this->currencyFormat(
            		12.3,
            		'EUR'
                     )."<br>";

                echo $this->translatePlural("Pessoa", "Pessoas", 10)

            ?>
        
        
        
        
        
        
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
